# 9_1 Unrecoverable Errors with `panic!`

- Rust에는 `panic!` macro가 있습니다.
- panic하는 예시는 크게 2가지:
  - 명시적으로 `panic!` macro를 호출하는 경우
  - code가 panic하는 액션을 취하는 경우 (index out of range, ...)
- 기본적으로 panic할 때는 failure message를 출력하고, unwind하고, stack을 지우고
    프로그램을 종료합니다.
  - Environment variable을 설정하면, Rust로 하여금 call stack을 출력하게 만들어
      panic의 이유를 더 쉽게 디버깅할 수 있습니다.

### Unwinding the stack or Aborting in Response to a Panic

- panic이 발생하면, 기본적으로 _unwinding_이라는 과정을 거칩니다.
  - Rust가 stack을 거슬러 올라가 만났던 각 함수로부터의 data를 청소하는
      과정입니다.
  - 그러나 굉장히 많은 일을 해야 합니다.
- 따라서 Rust는 _aborting_ option을 제공합니다: clean up 없이 종료.
  - 그러면 OS가 memory를 청소하게 됩니다.
- Cargo.toml 설정 방법 예시:
  - profile section에 panic = 'abort'를 추가하는데, release mode일 때만
      적용되도록 합니다.
```toml
[profile.release]
panic = 'abort'
```

- panic 예시:
```rust
fn main() {
  panic!("crash and burn");
  // thread 'main' panicked at 'crash and burn', src/main.rs:2:3
  // note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
}
```
  - filename, line, column을 보여줍니다.
  - 따라서 우리의 코드가 아닌 다른 누군가의 코드에서 `panic!`이 발생했을 수도
      있습니다.
    - Backtrace를 통해 코드의 어느 파트가 문제가 되는지 알 수 있습니다.

## 9_1_2 `panic!` backtrace

- `panic!` call이 library로부터 오는 예시 (우리가 작성한 코드가 버그여서):
```rust
fn main() {
    let v = vec![1, 2, 3];

    v[99]; // Out of bounds (In C, not panic but UB. Buffer Overread. Security
           // Vulnerabilities.
    // thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 99', src/main.rs:4:5
    // note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    /*
    stack backtrace:
   0: rust_begin_unwind
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_bounds_check
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:84:5
   3: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:242:10
   4: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/slice/index.rs:18:9
   5: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/alloc/src/vec/mod.rs:2591:9
   6: panic::main
             at ./src/main.rs:4:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
    */
}
```
- Backtrace 정보를 얻으려면 반드시 debug 모드여야 합니다.
  - 6: panic::main 이 문제가 있다는 것을 보여주고 있습니다.
    - 이 경우 Out of range 문제를 없애야 합니다.
    - 나중에 다른 코드가 panic할 경우, 우리는 코드의 어떤 부분이 어떤 값을
        받아들여서 panic을 내는지 확인해야 하고, 코드가 실제로는 어떤 일을 해야
        하는지 알아내야 합니다.
