# 9_2 `Result`로 복구 가능한 에러 처리

많은 에러들은 프로그램 자체를 멈출 만큼 심각하지 않습니다. 함수가 실패했을 때,
그것(에러)은 종종 당신이 쉽게 해석하고 응답할 수 있는 이유가 됩니다. 예를 들어,
파일을 열려고 했는데 그 파일이 없어서 실패한다면, 프로세스를 종료하는 대신
파일을 생성하고 싶을 수 있습니다.

- Result definition
```rust
enum Result<T, E> {
    Ok(T),
    Err(E),
}
```
`T`, `E` 모두 generic type parameter입니다. `Result`가 이런 generic type
parameter들을 가지고 있기 때문에, `Result` type을 여러 type의 함수에 사용될 수
있으며 성공/실패 케이스마다 다른 타입을 반환하게 만들 수 있습니다.

- Ex)
```rust
use std::fs::File;
fn main() {
  let greeting_file_result = File::open("hello.txt"); // Result<T, E>
}
```
  - `T`는 `File::open`이 성공했을 때 반환되는 file handle type이고, `E`는
      `File::open` 이 실패했을 때 반환되는 `std::io:Error` type입니다.
  - 이 때 실패하는 이유는 여러 가지일 수 있습니다.
    - 파일이 존재하지 않는다.
    - 파일에 대한 권한이 없다.
  - `File::open` 함수는 성공/실패 여부도 반환해야 하지만, file handle / error
      information 중 하나를 함께 반환해야 합니다. 이를 위해 `Result` enum을 사용합니다.
```rust
use std::fs::File;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file, // returns file value
        Err(error) => panic!("Problem opening the file: {:?}", error),
    };
}
```
- `Result`는 `Option`과 마찬가지로 prelude에 들어있습니다. 따라서 `Result`를
    사용하기 위해서 `Result::`를 붙이지 않아도 됩니다.

## 9_2_1 Matching on Different Errors

- Failure 이유마다 서로 다른 동작을 취하고 싶습니다.
  - 파일이 없을 때: 파일을 만들고 새 파일 handle을 반환
  - 다른 이유로 실패했을 때: panic!

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file_result = File::open("hello.txt");

    let greeting_file = match greeting_file_result {
        Ok(file) => file,
        Err(error) => match error.kind() { // io::Error. kind()를 가짐.
            ErrorKind::NotFound => match File::create("hello.txt") {
                Ok(fc) => fc,
                Err(e) => panic!("Problem creating the file: {:?}", e),
            },
            other_error => {
                panic!("Problem opening the file: {:?}", other_error);
            }
        },
    };
}
```

- `match`를 중첩해서 사용하는 것은 코드가 복잡해지고, 가독성이 떨어지는 단점이
    있습니다. 이를 해결하기 위해 `Result`에는 `unwrap_or_else`라는 method가
    있습니다.
```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| { // lambda exp.
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
}
```
- 또한 Ch 13에서 Closure를 배우고 나면 `match`로 `Result<T, E>`를 다룰 때 더
    concise한 코드를 작성할 수 있습니다.

## 9_2_2 Shortcuts for Panic on Error: unwrap and expect

- `match`를 쓰는 것도 좋긴 하지만, verbose하며, 의도를 항상 잘 나타내지는
    못합니다.
- `Result<T, E>` 타입은 helper method를 많이 가지고 있어 다양하고 자세한 일들을
    많이 할 수 있습니다.
  - `unwrap`은 match와 같은 역할을 하기 위한 method입니다. `Result`가 `Ok`이면
      unwrap은 `Ok`의 값을 반환하고, `Err`이면 `panic!`을 호출합니다.
```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt").unwrap();
}
```
  - `expect`는 `unwrap`과 비슷하지만, `panic!`을 호출할 때 panic message를
      지정할 수 있습니다. 이를 통해 의도를 더 잘 나타내고, `panic!` 디버깅을 더
      쉽게 만들어줍니다.
```rust
use std::fs::File;

fn main() {
  let greeting_file = File::open("hello.txt")
      .expect("Failed to open hello.txt");
}
```
- Production에 나갈 코드를 작성할 때는, `unwrap`보다 `expect`를 사용하여 왜 이
    동작이 항상 성공해야 하는지에 대한 context를 더 잘 나타내는 것이 좋습니다.
  - 이를 통해, 가정이 틀렸다는 게 밝혀지면, 디버깅을 위한 정보를 더 많이 가지게
      됩니다.

## 9_2_3 Propagating Errors

- 함수의 어딘가가 실패했을 때, 함수 안에서 error handling을 하는 대신, 해당
    error를 반환하여 caller가 동작을 결정하게 할 수 있습니다.
- 이를 _propagating_이라고 부르며, caller에게 더 많은 권한을 부여합니다.
    caller가 로직에 대한 정보를 더 많이 가져서 error를 어떻게 처리해야 하는지에
    대한 context를 더 잘 알 수 있기 때문입니다.
- 자세한 예시 (이걸 이해하고 나서 더 짧은 버전을 보는 게 좋습니다):
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let username_file_result = File::open("hello.txt");

    let mut username_file = match username_file_result {
        Ok(file) => file,
        Err(e) => return Err(e), // error 반환
    };

    let mut username = String::new();

    match username_file.read_to_string(&mut username) {
        Ok(_) => Ok(username),
        Err(e) => Err(e), // error 반환. 마지막 expression이라서 return 생략
    }
}
```
  - Return type `Result<String, io:Error>`는 `Ok`일 때 `String`을 반환하고,
      `Err`일 때 `io::Error`를 반환합니다.
    - `io:Error`를 선택한 이유는 error value를 반환하기 때문입니다.
      - 두 종류의 에러: `File::open` / `.read_to_string`

### 9_2_3_1 Shortcuts for Propagating Errors: `?` Operator
- 위와 같이, Rust에서 Error propagation은 상당히 자주 일어납니다. 따라서
    Rust에서는 `?`를 이 용도로 사용할 수 있도록 만들었습니다.
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username_file = File::open("hello.txt")?;
    let mut username = String::new();
    username_file.read_to_string(&mut username)?;
    Ok(username)
}
```
  - `Result` value 바로 뒤에 놓인 `?`는 `match`와 비슷한 동작을 합니다.
    - `Ok`일 때는 `Ok`의 value를 expression으로부터 반환합니다.
    - `Err`일 때는 `Err`의 value를 함수 전체로부터 반환합니다.
  - `match` 와의 차이점:
    - `?`를 통해 호출된 error value는 `from` function을 통해 반환되는데, `from`
        function은 `From` trait을 통해 구현되며, 이 함수는 value의 타입을 바꾸는
        데에 사용됩니다.
      - `?`가 `from` function을 호출할 경우, from 함수의 input으로 들어온 error
          type이 강제로 현재 들어있는 함수의 error return type으로 바뀝니다.
      - 이를 통해 function이 하나의 에러 타입으로 모든 에러를 표현할 수 있도록
          도와줍니다.
    - Ex) Error 반환을 위해 `OurError` 타입을 정의하고, `impl From<io::Error>
        for OurError`를 정의하여 `io:Error`로부터 `OurError` 타입의 instance를
        만드는 방법을 정의한다면, `?`가 `from`을 호출하여 `OurError` 타입으로
        자동으로 변환해줍니다.
  - `?` operator를 통해 많은 양의 boilerplate를 지울 수 있으며 구현을 간략화할
      수 있습니다.
  - 위의 코드를 더 줄이면 다음과 같습니다.
```rust
use std::fs::File;
use std::io::{self, Read};

fn read_username_from_file() -> Result<String, io::Error> {
    let mut username = String::new();

    File::open("hello.txt")?.read_to_string(&mut username)?;
    // username_file 변수를 만들지 않고도 바로 method chaining을 할 수 있습니다.
    Ok(username)
}
```
- 마지막으로 `std::fs::read_to_string`을 직접 사용하여 코드를 더 줄일 수
    있습니다. (file handle을 open으로 열고, read_to_string으로 읽는 대신)
```rust
use std::fs;
use std::io;

fn read_username_from_file() -> Result<String, io::Error> {
    fs::read_to_string("hello.txt")
}
```
- 물론 이렇게 코드를 줄이는 과정에서 error handling을 설명할 기회가
    사라졌기 때문에, 맨 처음에 긴 버전을 넣어서 error handling이 어떻게
    일어나는지를 설명했습니다.

### 9_2_3_2 Where the `?` operator can be used

- `?`는 `?`가 사용된 값의 타입과 return type이 compatible한 함수에서만 사용할 수
    있습니다.
  - `?` 가 early return 을 하기 때문입니다.
```rust
use std::fs::File;

fn main() {
    let greeting_file = File::open("hello.txt")?; // Error: main doesn't have a
                                                  // return type of the `Result`
                                                  // value of `File::open`.
}
```
  - 구체적으로, `?`는 `Result`, `Option`, 또는 `FromResidual`을 구현한
      타입에서만 사용할 수 있습니다.

- 에러를 수정하기 위한 두 가지 방법:
  - `?` operator를 사용했을 때의 return type과 compatible하게 함수 signature
      수정 (제한이 없을 경우)
  - `match`를 쓰거나, 다른 `Result<T, E>`의 method를 써서 `Result<T, E>`를
      올바른 방식으로 다루기
  - 위에서 `?`는 `Option<T>` 타입과도 compatible하다는 에러 메세지를 보았습니다.

- `Option<>`을 반환하는 함수에서는 `Option` 타입의 값에만 `?`를 쓸 수 있습니다.
  - Value가 `None`이면, `?`는 `None`을 return 합니다.
  - Value가 `Some`이면, `?`는 `Some`의 value를 return 합니다.
- Ex)
```rust
fn last_char_of_first_line(text: &str) -> Option<char> {
    text.lines().next()?.chars().last() // character가 없을 경우,
    // text.lines().next() 의 반환값 Option<&str> 에서 None을 return 합니다.
    // character가 있을 경우 &str 타입의 값을 반환하며, `chars()`를 불러서
    // iterator를 생성하며, 마지막으로 `last()`를 통해 마지막 character를
    // return 합니다.
}
```

- `Result` 타입의 함수에서는 `Result` 값에 `?`를 쓸 수 있고, `Option` 타입의
    함수에서는 `Option` 값에 `?`를 쓸 수 있습니다. 이것들을 섞어쓸 수 **없습니다**.
  - `?`는 `Result`를 `Option`으로 바꾸거나, `Option`을 `Result`로 바꾸는
      것을 허용하지 않습니다.
  - `Result` 의 `ok` method나 `Option`의 `ok_or` method를 사용해서
      `Result`를 `Option`으로 바꾸거나, `Option`을 `Result`로 바꿀 수 있습니다.

- `main` function은 프로그램의 시작점이자 끝점이기 때문에, 프로그램이 예상한
    대로 동작하게 하기 위해 return type에 제약이 있습니다.
  - 이들 중 가능한 것에는 `Result<(), E>`가 있습니다. 따라서 `main` function에서
      `?`를 쓰도록 바꿀 수 있습니다.

```rust
use std::error::Error;
use std::fs::File;

fn main() -> Result<(), Box<dyn Error>> {
    let greeting_file = File::open("hello.txt")?;

    Ok(())
}
```
  - `Box<dyn Error>` 타입은 _trait object_인데, 이를 Chapter 17에서 다룹니다.
      지금 시점에서는 `Box<dyn Error`를 어떤 타입의 에러든 가능한 것으로
      생각하면 도움이 될 것입니다.
    - 지금은 main에서 `std::io::Error` 타입만 반환하지만, signature를 이렇게
        정의해둠으로서 `main`에서 다른 타입의 에러를 반환하게 되어도 문제가
        생기지 않습니다.
- `main` 에서 `Result<(), E>`를 반환할 경우, main이 `Ok(())` 를 반환하면
    프로그램이 0을 반환하며 종료되고, `Err(e)`를 반환하면 프로그램이 0이 아닌
    값을 반환하면 종료됩니다.
  - 이는 C 프로그램과의 convention과 호환하기 위함입니다. C에서도 0 혹은 0이
      아닌 값을 반환하며 종료되기 때문입니다.

- 이외에도 `main` function은 `std::process:Termination` trait을 구현한 어떤
    타입이든 반환할 수 있습니다.
  - 이 타입들은 `report` 함수를 가지고 있으며 이 함수는 `ExitCode`를 반환합니다.
  - `Termination` trait을 구현하기 위해선 standard library를 참조하세요.

## 9_2_4 Summary
- `panic!`을 부르는 것과 `Result`를 반환하는 것을 자세하게 살펴보았습니다.
- 어떤 경우에 어떤 것을 쓰는 것이 올바른지 9_3에서 알아봅니다.
